use std::collections::BTreeMap;

pub type HookMap = BTreeMap<Hook, i32>;

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Hook {
    AppBooting,
    AppBooted,
    RequestReceived,
    BeforePostList,
    AfterPostList,
    BeforePostCreate,
    AfterPostCreate,
    BeforePostUpdate,
    AfterPostUpdate,
    BeforePostDelete,
    AfterPostDelete,
    BeforePageList,
    AfterPageList,
    BeforePageCreate,
    AfterPageCreate,
    BeforeCommentCreate,
    AfterCommentCreate,
    BeforeCommentModerate,
    AfterCommentModerate,
    BeforeAuthLogin,
    AfterAuthLogin,
    BeforeAuthRegister,
    AfterAuthRegister,
    BeforeAuthBootstrap,
    AfterAuthBootstrap,
    BeforeSettingsRead,
    AfterSettingsRead,
    BeforeSettingsUpdate,
    AfterSettingsUpdate,
    BeforeTermCreate,
    AfterTermCreate,
    BeforeTermUpdate,
    AfterTermUpdate,
    BeforeTermDelete,
    AfterTermDelete,
    BeforePostTermsSync,
    AfterPostTermsSync,
    BeforeRender,
    AfterRender,
    FrontendHead,
    FrontendHeader,
    FrontendFooter,
    FrontendAuthForm,
    FrontendCommentForm,
    FrontendPostContent,
    AdminMenu,
}
