#[path = "entities/comments.rs"]
pub mod comments;
#[path = "entities/options.rs"]
pub mod options;
#[path = "entities/post_revisions.rs"]
pub mod post_revisions;
#[path = "entities/post_terms.rs"]
pub mod post_terms;
#[path = "entities/posts.rs"]
pub mod posts;
#[path = "entities/terms.rs"]
pub mod terms;
#[path = "entities/users.rs"]
pub mod users;
